---
- hosts: localhost
  become: yes
  tasks:
  - name: Install Python and pip
    package:
      name: python3
      state: present
  - name: Install Python dependencies
    pip:
      name: "{{ item }}"
      state: present
    with_items:
      - flask
      - Flask
      - requests
      - torch
      - torchvision
      - PIL
  - name: Install Node.js and npm
    package:
      name: nodejs
      state: present
  - name: Install React dependencies
    npm:
      name: "{{ item }}"
      state: present
    with_items:
      - react
      - react-dom
      - react-dropzone
      - axios
      - react-scripts
      - web-vitals
